name: Build Mimosa iOS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Generate build configuration
        run: |
          cd $GITHUB_WORKSPACE
          mkdir -p build-input/configuration-repository
          ./build-system/example-generate-configuration build-input/configuration-repository
          echo 'module(name = "build_configuration")' > build-input/configuration-repository/MODULE.bazel
          echo "=== CONFIGURATION CHECK ==="
          ls -la build-input/configuration-repository
          cat build-input/configuration-repository/MODULE.bazel
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install tools
        run: |
          brew install bazelisk

      - name: Check bazel
        run: |
          bazelisk version

      - name: Generate configuration
        run: |

      - name: Generate configuration
        run: |
          mkdir -p build-input/configuration-repository
          ./build-system/example-generate-configuration build-input/configuration-repository

      - name: Build iOS
        run: |
          bazelisk build \
          //Telegram:Telegram

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: Mimosa-iOS-build
          path: bazel-bin/**
