name: Test Release

on:
  workflow_dispatch:

jobs:
  release-test:
    runs-on: ubuntu-latest

    steps:
      - name: Create test release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test-${{ github.run_number }}
          release_name: Test ${{ github.run_number }}
          draft: false
          prerelease: true
